name: GitHub Deprecation Scanner
description: Checks logs for deprecated usage and reports them as GitHub Actions warnings
author: ylazakovich

runs:
  using: "composite"
  steps:
    - run: ./entrypoint.sh "${{ inputs.log_file }}"
      shell: bash