name: "Run Github Action"
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: 🔨Checkout code
        uses: actions/checkout@v4
      - name: 🚀 Run Scanner
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ./
